// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8d6j_XsmcPa9U-9HRrhAcI35gpaMZ55k',
    appId: '1:825212863486:web:3dcf766f606251c70d76af',
    messagingSenderId: '825212863486',
    projectId: 'goaltracker-35bbd',
    authDomain: 'goaltracker-35bbd.firebaseapp.com',
    storageBucket: 'goaltracker-35bbd.firebasestorage.app',
    measurementId: 'G-3E9NR4N7PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAodhKkYNvsb4EHoknE161Wjt89pM-pm5g',
    appId: '1:825212863486:android:2dbf97646647dab50d76af',
    messagingSenderId: '825212863486',
    projectId: 'goaltracker-35bbd',
    storageBucket: 'goaltracker-35bbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUWKMAWdmWx4BeAOipq3UPwLdLAG96wI',
    appId: '1:825212863486:ios:bfe2267c4911c7130d76af',
    messagingSenderId: '825212863486',
    projectId: 'goaltracker-35bbd',
    storageBucket: 'goaltracker-35bbd.firebasestorage.app',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUWKMAWdmWx4BeAOipq3UPwLdLAG96wI',
    appId: '1:825212863486:ios:bfe2267c4911c7130d76af',
    messagingSenderId: '825212863486',
    projectId: 'goaltracker-35bbd',
    storageBucket: 'goaltracker-35bbd.firebasestorage.app',
    iosBundleId: 'com.example.habittracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8d6j_XsmcPa9U-9HRrhAcI35gpaMZ55k',
    appId: '1:825212863486:web:f25eb1215204caed0d76af',
    messagingSenderId: '825212863486',
    projectId: 'goaltracker-35bbd',
    authDomain: 'goaltracker-35bbd.firebaseapp.com',
    storageBucket: 'goaltracker-35bbd.firebasestorage.app',
    measurementId: 'G-85QS93JKWN',
  );
}
